[package]
name = "OpenGL"
version = "0.1.0"
edition = "2021"

[dependencies]
rand = "0.8.5"
beryllium = "0.13.3"
# bytemuck = "1.16.1"
# imagine = "0.5.1"
# ogl33 = "0.3.0"
imagine = "0.0.5"
bytemuck = "1"
ogl33 = { version = "0.2.0", features = ["debug_error_checks"]}
